#!/usr/bin/env python3

import colors as c
import pfudor as quiz
import random

print(c.clear + quiz.intro)

while quiz.questions:
    question_function = random.choice(quiz.questions)
    is_correct = question_function()
    if is_correct:
        quiz.questions.remove(question_function)
