#!/usr/bin/env python3

import time
import colors as c
import random

hundred = 1
seconds = 0
minutes = 0
hours = 0
days = 0
weeks = 0

print('Control-C to stop')

while True:
    time.sleep(.01)
    print(c.clear + c.magenta + 'Press Control-C to stop')
    print(c.red)
    print('Weeks:')
    print(weeks)
    print(c.orange)
    print('Days:')
    print(days)
    print(c.yellow)
    print("Hours:")
    print(hours)
    print(c.green)
    print('Minutes:')
    print(minutes)
    print(c.blue)
    print('Seconds:')
    print(seconds)
    print(c.violet)
    print('Hundredths:')
    print(hundred)
    hundred += 1
    if hundred == 100:
        seconds += 1
        hundred -= 100
    if seconds == 60:
        minutes += 1
        seconds -= 60
    if minutes == 60:
        hours += 1
        minutes -= 60
    if hours == 24:
        days += 1
        hours -= 24
    if days == 7:
        weeks += 1
        days -= 7
